const one_e_dmg_ruleset = {
  "{\"id\":\"grassland\",\"tileset_id\":\"default\"}":[
    {"key":"{\"id\":\"grassland\",\"tileset_id\":\"default\"}","weight":11},
    {"key":"{\"id\":\"scrubland\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"forest\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"badlands\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"desert\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"hills\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"mountains\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"marsh\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"water\",\"tileset_id\":\"default\"}","weight":1}
  ],
  "{\"id\":\"scrubland\",\"tileset_id\":\"default\"}":[
    {"key":"{\"id\":\"grassland\",\"tileset_id\":\"default\"}","weight":3},
    {"key":"{\"id\":\"scrubland\",\"tileset_id\":\"default\"}","weight":8},
    {"key":"{\"id\":\"forest\",\"tileset_id\":\"default\"}","weight":2},
    {"key":"{\"id\":\"badlands\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"desert\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"hills\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"mountains\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"marsh\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"water\",\"tileset_id\":\"default\"}","weight":1}
  ],
  "{\"id\":\"forest\",\"tileset_id\":\"default\"}":[
    {"key":"{\"id\":\"grassland\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"scrubland\",\"tileset_id\":\"default\"}","weight":3},
    {"key":"{\"id\":\"forest\",\"tileset_id\":\"default\"}","weight":10},
    {"key":"{\"id\":\"badlands\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"hills\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"mountains\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"marsh\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"water\",\"tileset_id\":\"default\"}","weight":1}
  ],
  "{\"id\":\"water\",\"tileset_id\":\"default\"}":[
    {"key":"{\"id\":\"water\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"marsh\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"grassland\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"hills\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"mountains\",\"tileset_id\":\"default\"}","weight":1}
  ],
  "{\"id\":\"hills\",\"tileset_id\":\"default\"}":[
    {"key":"{\"id\":\"grassland\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"scrubland\",\"tileset_id\":\"default\"}","weight":2},
    {"key":"{\"id\":\"forest\",\"tileset_id\":\"default\"}","weight":2},
    {"key":"{\"id\":\"badlands\",\"tileset_id\":\"default\"}","weight":2},
    {"key":"{\"id\":\"desert\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"hills\",\"tileset_id\":\"default\"}","weight":6},
    {"key":"{\"id\":\"mountains\",\"tileset_id\":\"default\"}","weight":2},
    {"key":"{\"id\":\"marsh\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"water\",\"tileset_id\":\"default\"}","weight":2}
  ],
  "{\"id\":\"mountains\",\"tileset_id\":\"default\"}":[
    {"key":"{\"id\":\"grassland\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"scrubland\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"forest\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"badlands\",\"tileset_id\":\"default\"}","weight":2},
    {"key":"{\"id\":\"desert\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"hills\",\"tileset_id\":\"default\"}","weight":4},
    {"key":"{\"id\":\"mountains\",\"tileset_id\":\"default\"}","weight":8},
    {"key":"{\"id\":\"water\",\"tileset_id\":\"default\"}","weight":1}
  ],
  "{\"id\":\"badlands\",\"tileset_id\":\"default\"}":[
    {"key":"{\"id\":\"grassland\",\"tileset_id\":\"default\"}","weight":2},
    {"key":"{\"id\":\"scrubland\",\"tileset_id\":\"default\"}","weight":2},
    {"key":"{\"id\":\"forest\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"badlands\",\"tileset_id\":\"default\"}","weight":3},
    {"key":"{\"id\":\"desert\",\"tileset_id\":\"default\"}","weight":2},
    {"key":"{\"id\":\"hills\",\"tileset_id\":\"default\"}","weight":5},
    {"key":"{\"id\":\"mountains\",\"tileset_id\":\"default\"}","weight":2},
    {"key":"{\"id\":\"marsh\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"water\",\"tileset_id\":\"default\"}","weight":1}
  ],
  "{\"id\":\"desert\",\"tileset_id\":\"default\"}":[
    {"key":"{\"id\":\"grassland\",\"tileset_id\":\"default\"}","weight":3},
    {"key":"{\"id\":\"scrubland\",\"tileset_id\":\"default\"}","weight":2},
    {"key":"{\"id\":\"badlands\",\"tileset_id\":\"default\"}","weight":3},
    {"key":"{\"id\":\"desert\",\"tileset_id\":\"default\"}","weight":6},
    {"key":"{\"id\":\"hills\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"mountains\",\"tileset_id\":\"default\"}","weight":2},
    {"key":"{\"id\":\"marsh\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"water\",\"tileset_id\":\"default\"}","weight":1}
  ],
  "{\"id\":\"marsh\",\"tileset_id\":\"default\"}":[
    {"key":"{\"id\":\"grassland\",\"tileset_id\":\"default\"}","weight":2},
    {"key":"{\"id\":\"scrubland\",\"tileset_id\":\"default\"}","weight":2},
    {"key":"{\"id\":\"forest\",\"tileset_id\":\"default\"}","weight":2},
    {"key":"{\"id\":\"badlands\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"hills\",\"tileset_id\":\"default\"}","weight":1},
    {"key":"{\"id\":\"marsh\",\"tileset_id\":\"default\"}","weight":7},
    {"key":"{\"id\":\"water\",\"tileset_id\":\"default\"}","weight":4}
  ],
}

export { one_e_dmg_ruleset }